FROM initrd-builder:0.0.1 AS builder

COPY /* /home/ubuntu/

WORKDIR /home/ubuntu

RUN touch .placeholder && \
	mkdir extracted && \
	ls *deb | \
		xargs -I@ dpkg -x @ extracted && \
	extract-vmlinux extracted/boot/vmlinuz-* > extracted/vmlinux && \
	cd extracted && \
	/opt/initrd-builder/create.sh

FROM scratch

COPY --from=builder /home/ubuntu/extracted/vmlinux /boot/
COPY --from=builder /home/ubuntu//out/initrd /boot/
COPY --from=builder /home/ubuntu/.placeholder /lib/modules/

